### ISSUE TITLE
After swiping, console error of this.props.remove cannot read property props of undefined

### ISSUE THREAD

**Issue by creationator** [hosembafer/react-swipe-to-dismiss#7]
I was trying to use the swipe-to-dismiss npm package for my react app. I noticed that you were one of the collaborators on it. I was reaching out because I was experiencing an error when I tried using it. For the most part, the functionality worked as expected but only one problem, once I swiped my component off the screen the element wasn't actually deleted from the dom (It just left an empty space) and returned an error of "TypeError: Cannot read property 'props' of undefined".

I've tried a couple of other solutions such as placement, removing 'this' and even 'props'. I went ahead as to so far add the absolute path to the node_modules  directory but nothing works. I was wondering if anyone else using this had experienced this issue and if so what was there fix.

**Comment by hosembafer** [comment]
I'll investigate and release a fix today

**Comment by creationator** [comment]
Awesome thanks. Also, just a suggestion can the package also support swiping on mobile devices.

**Comment by hosembafer** [comment]
Yeah, check out this #4 , want to find time in upcoming month for it.

**Comment by hosembafer** [comment]
@creationator can you provide an example in CodeSandbox?

**Comment by creationator** [comment]
Awesome!!!!! Thanks. I

**Comment by hosembafer** [comment]
@creationator is problem solved? Can we close this?

**Comment by creationator** [comment]
Yes you can close it.

**Comment by hosembafer** [comment]
So how you solved it? I found that error only in case when we copying example code and missing handle this.props.remove.
